name: Continuous Delivery

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        node-version: '20'

    - name: Build Docker Image
      run: docker build -t gabrielaherra/deploy_breast_cancer:v1 .

    - name: Docker push to DockerHub
      run: docker push gabrielaherra/deploy_breast_cancer:v1

    - name: Login into the server
      run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

    - name: SSH into AWS EC2 Instance and Update Docker Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker login 
          if docker ps --all | grep breast-cancer; then
            docker stop breast-cancer
            docker rm breast-cancer
          fi
    
          docker pull ${{ secrets.DOCKER_USERNAME }}/deploy-breast-cancer:v1
          docker run -d --name breast-cancer -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/deploy-breast-cancer:v1